/// <reference types="@types/node" />

import alchemy from "alchemy";
import { RandomString } from "alchemy/random";
import { Container, R2Bucket, BunSPA, Worker } from "alchemy/cloudflare";
import { CloudflareStateStore, SQLiteStateStore } from "alchemy/state";
import { MinecraftContainer } from "./src/container.ts";

const app = await alchemy("cloudflare-container", {
  stateStore: (scope) => new CloudflareStateStore(scope),
  password: process.env.ALCHEMY_PASSWORD ?? "minecraft-on-cloudflare-is-awesome-this-is-used-to-encrypt-secrets-stored-in-cloudflare-state-but-we-dont-have-any-sensitive-secrets-so-its-fine-to-use-this-password",
});

export const container = await Container<MinecraftContainer>("container3", {
  name: `${app.name}-container`,
  className: "MinecraftContainer",
  adopt: true,
  build: {
    context: 'container_src',
    dockerfile: "Dockerfile",
  },
  instanceType: "standard-4"
});



// R2 bucket for Dynmap tiles and web UI
const dynmapBucket = await R2Bucket("dynmap-tiles", {
  name: `${app.name}-dynmap`,
  dev: {
    remote: true,
  },
  adopt: true,
  // Enable public access - tiles and UI served directly from R2.dev domain
  allowPublicAccess: true,
  // CORS config allows browser JS to fetch tiles and call Worker API
  cors: [
    {
      allowed: {
        origins: ["*"], // Permissive CORS for ease of use
        methods: ["GET", "HEAD"],
        headers: ["*"],
      },
    },
  ],
  lifecycle: [
    {
      id: "delete-after-1-day",
      enabled: true,
      conditions: {
          prefix: "tiles/world/",
      },
      deleteObjectsTransition: {
        condition: {
          maxAge: 60 * 60 * 12, // 12 hours
          type: "Age",
        }
      }
    }
  ]
});

// Create API token for R2 access (S3-compatible credentials)
// This generates accessKeyId and secretAccessKey for Dynmap's S3 SDK
// const r2Token = await AccountApiToken("dynmap-r2-token", {
//   name: `${app.name}-dynmap-r2`,
//   policies: [
//     {
//       effect: "allow",
//       permissionGroups: ["Workers R2 Storage Write"],
//       resources: {
//         "com.cloudflare.api.account": "*",
//       },
//     },
//   ],
// });

export const dynmapWorker = await Worker("dynmap-worker", {
  name: `${app.name}-dynmap-worker`,
  entrypoint: "src/dynmap-worker.ts",
  adopt: true,
  bindings: {
    DYNMAP_BUCKET: dynmapBucket,
    BUCKET_DOMAIN: dynmapBucket.domain ?? "",
    MINECRAFT_WORKER_URL: "https://*", // should be worker url but we don't know it yet
  },
});

export const worker = await BunSPA("minecraft-site", {
  name: `${app.name}-worker`,
  entrypoint: "src/worker.ts",
  frontend: "index.html",
  adopt: true,
  compatibility: "node",
  compatibilityFlags: ["enable_ctx_exports"],
  compatibilityDate: "2025-09-27",
  bindings: {
    MINECRAFT_CONTAINER: container,
    // DYNMAP_BUCKET: dynmapBucket,

    // Secrets for Tailscale
    TS_AUTHKEY: alchemy.secret(process.env.TS_AUTHKEY || "null"),
    NODE_ENV: process.env.NODE_ENV ?? 'development',

    // R2 API credentials (S3-compatible) generated by AccountApiToken
    // These are automatically encrypted by alchemy.secret()
    // R2_ACCESS_KEY_ID: r2Token.accessKeyId,
    // R2_SECRET_ACCESS_KEY: r2Token.secretAccessKey,

    // R2 S3-compatible endpoint URL for container
    R2_ENDPOINT: `https://${process.env.CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com`,

    // Bucket name (passed to container for Dynmap config)
    R2_BUCKET_NAME: dynmapBucket.name,

    R2_BUCKET: dynmapBucket,
    
    // Dynmap worker URL for iframe embedding
    DYNMAP_WORKER_URL: dynmapWorker.url ?? "",
  },
});

console.log("Worker URL:", worker.url);
console.log("Dynmap URL:", `https://${dynmapBucket.domain}`);
console.log("Dynmap Worker URL:", dynmapWorker.url);

await app.finalize();
